# -*- coding: utf-8 -*-
"""Movies Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbytCo5K-EvbH2EjKU9-L90qSgzOSnoV
"""

import PyPDF2
from PyPDF2 import PdfReader

reader = PdfReader('/content/Movie and TV Show Recommendations.pdf')

all_text = ''
for page in reader.pages:
    all_text += page.extract_text()

text_lines = all_text.split('\n')

movie_info = []
current_movie = {}

for line in text_lines:

    if line.strip().startswith(('1. ', '2. ', '3. ', '4. ', '5. ', '6. ', '7. ', '8. ', '9. ', '10. ', '11. ', '12. ', '13. ', '14. ', '15. ',
                                '16. ', '17. ', '18. ', '19. ', '20. ', '21. ', '22. ', '23. ', '24. ', '25. ', '26. ', '27. ', '28. ', '29. ', '30. ',
                                '31.', '32.', '33.','34.', '35.', '36.', '37.', '38.', '39.', '40.', '41.', '42.', '43.',
                                '44. ', '45. ', '46. ', '47. ', '48. ', '49. ')):

        if current_movie:
            movie_info.append(current_movie)
            current_movie = {}


        s_no, movie_title = line.split('. ', 1)
        current_movie['S.No'] = s_no
        current_movie['Movie Name'] = movie_title.strip()
    elif line.startswith('Genre:  '):
        current_movie['Genre'] = line.replace('Genre:  ', '').strip()
    elif line.startswith('Status:  '):
        current_movie['Status'] = line.replace('Status:  ', '').strip()
    elif line.startswith('Description:  '):
        current_movie['Description'] = line.replace('Description:  ', '').strip()


if current_movie:
    movie_info.append(current_movie)

# Print the movie information
for movie in movie_info:
    print("S.No:", movie.get('S.No', ''))
    print("Movie Name:", movie.get('Movie Name', ''))
    print("Description:", movie.get('Description', ''))
    print("Genre:", movie.get('Genre', ''))
    print("Status:", movie.get('Status', ''))
    print()

# Print the last movie separately
if movie_info:
    last_movie = movie_info[-1]
    print("Last Movie:")
    print("S.No:", last_movie.get('S.No', ''))
    print("Movie Name:", last_movie.get('Movie Name', ''))
    print("Description:", last_movie.get('Description', ''))
    print("Genre:", last_movie.get('Genre', ''))
    print("Status:", last_movie.get('Status', ''))

# Optionally, you can also print the entire movie_info list
print(movie_info)

df = pd.DataFrame(data = movie_info, columns = {'S.No':'S.No', 'Movie Name':'Movie Name', 'Genre':'Genre', 'Status':'Status', 'Description':'Description'} )

df

print(df.dtypes)

df = df.astype({'S.No':int})

print(df.dtypes)

file = 'Output.csv'
df.to_csv(file,index = False)
print(f'The Dataframe is Saved as {file}')

df1 = pd.read_csv('Output.csv')

df1

